apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  # the class name comes from the storage class we defined before
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 6Gi

# NEED FOR PVC
# 1. Dynamic volume provisioning allows storage volumes to be created on-demand. 
# 2. Without dynamic provisioning, cluster administrators have to manually make calls to their cloud or storage provider to create new storage volumes, and then create PersistentVolume objects to represent them in k8s
# 3. The dynamic provisioning feature eliminates the need for cluster administrators to pre-provision storage. Instead, it automatically provisions storage when it is requested by users.